---
name: Pull Request
about: Create a pull request.
title: '[Pull Request]'

---
body:
  - type: textarea
    attributes:
      label: Description
      description: Briefly describe the purpose of this pull request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Changes Made
      description: Provide a list of changes made in this pull request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Related Issues
      description: Reference any related issues using keywords like "Fixes #issue-number".
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Notes
      description: Add any other notes or screenshots that might be helpful for the reviewers.
    validations:
      required: false
