services:
  csclub-website:
    image: csclub-website:latest
    container_name: csclub-website
    env_file:
      - .env.local
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - csclub

networks:
  csclub:
    external: true
