FROM node:20-alpine3.18 as builder

ENV CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
ENV DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}
ENV DATABASE_URL=${DATABASE_URL}
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
ENV NEXT_PUBLIC_DRIVE_LINK=${NEXT_PUBLIC_DRIVE_LINK}
ENV REDIS_URI=${REDIS_URI}
ENV SQUARE_ACCESS_TOKEN=${SQUARE_ACCESS_TOKEN}
ENV SQUARE_LOCATION_ID=${SQUARE_LOCATION_ID}

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
ENV NODE_ENV production
ENV PORT 80
EXPOSE 80
CMD [ "npm","run","start" ]