import { Archivo } from 'next/font/google';
import Navbar from '@/components/Navbar';
import '@/styles/globals.css';

const ARCHIVO = Archivo({
    subsets: ['latin'],
    display: 'swap',
});

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en" className={ARCHIVO.className}>
            <body className="flex justify-center bg-primary-bg">
                <Navbar />
                {children}
            </body>
        </html>
    );
}

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
