/**
 * Seed-cms.ts
 *
 * Seeds the local Payload CMS via its REST API (http://localhost:4000).
 *
 * Usage: pnpm run db:seed-cms
 *
 * Requirements: Payload CMS must be running on http://localhost:4000
 */

const BASE_URL = process.env.PAYLOAD_URL || 'http://localhost:4000';
const EMAIL = process.env.PAYLOAD_EMAIL || 'admin@admin.com';
const PASSWORD = process.env.PAYLOAD_PASSWORD || 'password';

// ---------------------------------------------------------------------------
// HTTP helpers
// ---------------------------------------------------------------------------

let token: string | null = null;

async function login() {
    const res = await fetch(`${BASE_URL}/api/users/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: EMAIL, password: PASSWORD }),
    });
    if (!res.ok) throw new Error(`Login failed: ${res.status} ${await res.text()}`);
    const data = (await res.json()) as { token: string };
    token = data.token;
    console.log('  ✓ Logged in as', EMAIL);
}

async function api<T>(method: string, path: string, body?: unknown): Promise<T> {
    const res = await fetch(`${BASE_URL}/api${path}`, {
        method,
        headers: {
            'Content-Type': 'application/json',
            ...(token ? { Authorization: `JWT ${token}` } : {}),
        },
        body: body ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) {
        const text = await res.text();
        throw new Error(`${method} ${path} → ${res.status}: ${text}`);
    }
    return res.json() as Promise<T>;
}

/**
 * Upload a placeholder PNG as a Payload media document.
 *
 * Step 1: POST multipart — uploads a solid-color PNG (generated by sharp). Payload stores the file
 * and records width/height/filesize correctly. Step 2: PATCH the returned ID — sets
 * alt/type/eventName. Extra FormData fields are not reliably persisted in the same request, and
 * filterOptions on relationship fields (e.g. logo → type=sponsor) validate these fields at save
 * time, so they must be set first.
 */
async function uploadPlaceholderMedia(opts: {
    alt: string;
    type: 'sponsor' | 'event' | 'project' | 'gallery';
    eventName?: string;
    label: string;
    bgColor?: string;
    /** Width for PNG, defaults to 800 */
    width?: number;
    /** Height for PNG, defaults to 450 */
    height?: number;
}): Promise<string> {
    const { alt, type, eventName, label, bgColor = '#1a1a2e', width = 800, height = 450 } = opts;

    // Parse hex colour → RGB for sharp
    const hex = bgColor.replace('#', '');
    const r = parseInt(hex.slice(0, 2), 16);
    const g = parseInt(hex.slice(2, 4), 16);
    const b = parseInt(hex.slice(4, 6), 16);

    // Generate a solid-colour PNG in memory — no temp files needed
    const { default: sharp } = await import('sharp');
    const pngBuffer = await sharp({
        create: {
            width,
            height,
            channels: 3,
            background: { r, g, b },
        },
    })
        .png()
        .toBuffer();

    const filename =
        label
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-|-$/g, '') + '.png';

    // Step 1 — upload the PNG file
    // Use Uint8Array to avoid the Buffer → SharedArrayBuffer Blob type mismatch
    const form = new FormData();
    form.append('file', new Blob([new Uint8Array(pngBuffer)], { type: 'image/png' }), filename);

    const uploadRes = await fetch(`${BASE_URL}/api/media`, {
        method: 'POST',
        headers: { ...(token ? { Authorization: `JWT ${token}` } : {}) },
        body: form,
    });

    if (!uploadRes.ok) {
        const text = await uploadRes.text();
        throw new Error(`Upload media "${label}" → ${uploadRes.status}: ${text}`);
    }
    const { doc } = (await uploadRes.json()) as { doc: { id: string } };

    // Step 2 — PATCH to set alt / type / eventName so filterOptions validation passes
    const patchBody: Record<string, unknown> = { alt, type };
    if (eventName) patchBody.eventName = eventName;

    await api('PATCH', `/media/${doc.id}`, patchBody);

    return doc.id;
}

async function deleteAll(collection: string) {
    // Fetch published docs + draft-only docs and delete each.
    const [published, drafts] = await Promise.all([
        api<{ docs: Array<{ id: string }> }>('GET', `/${collection}?limit=500`),
        api<{ docs: Array<{ id: string }> }>('GET', `/${collection}?limit=500&draft=true`),
    ]);

    // Deduplicate IDs (draft query also returns published)
    const ids = new Set([...published.docs.map((d) => d.id), ...drafts.docs.map((d) => d.id)]);

    for (const id of ids) {
        try {
            await api('DELETE', `/${collection}/${id}`);
        } catch {
            // Ignore — already gone
        }
    }
    console.log(`  Cleared ${ids.size} records from ${collection}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
    console.log(`\n🌱 Seeding Payload CMS at ${BASE_URL}\n`);

    await login();

    // -------------------------------------------------------------------------
    // Clear existing data
    // -------------------------------------------------------------------------
    console.log('\n🗑  Clearing existing data...');
    for (const col of [
        'gallery',
        'events',
        'projects',
        'sponsors',
        'committee-members',
        'tech-stack',
        'media',
    ]) {
        await deleteAll(col);
    }

    // -------------------------------------------------------------------------
    // MEDIA — upload placeholder PNGs
    // -------------------------------------------------------------------------
    console.log('\n📁 Uploading placeholder media...');

    // Sponsor logos — 400×200 (wide landscape ratio, typical for company logos)
    const [idGoldLogo, idSilverLogo, idBronze1, idBronze2, idBronze3] = await Promise.all([
        uploadPlaceholderMedia({
            alt: 'Nexus Financial Logo',
            type: 'sponsor',
            label: 'Nexus Financial',
            bgColor: '#1a3a2e',
            width: 400,
            height: 200,
        }),
        uploadPlaceholderMedia({
            alt: 'QuantEdge Technologies Logo',
            type: 'sponsor',
            label: 'QuantEdge Technologies',
            bgColor: '#1a2a3e',
            width: 400,
            height: 200,
        }),
        uploadPlaceholderMedia({
            alt: 'Ironclad Systems Logo',
            type: 'sponsor',
            label: 'Ironclad Systems',
            bgColor: '#2e1a1a',
            width: 400,
            height: 200,
        }),
        uploadPlaceholderMedia({
            alt: 'Wavefront Analytics Logo',
            type: 'sponsor',
            label: 'Wavefront Analytics',
            bgColor: '#1a2e2e',
            width: 400,
            height: 200,
        }),
        uploadPlaceholderMedia({
            alt: 'Meridian Defence Logo',
            type: 'sponsor',
            label: 'Meridian Defence',
            bgColor: '#2e2a1a',
            width: 400,
            height: 200,
        }),
    ]);

    // Event banners — 1200×630 (standard OG/social banner ratio)
    const [idBannerHackathon, idBannerWorkshop, idBannerStudy, idBannerNetworking, idBannerSocial] =
        await Promise.all([
            uploadPlaceholderMedia({
                alt: 'Annual Hackathon Banner',
                type: 'event',
                label: 'Annual Hackathon 2026',
                bgColor: '#1a1a3e',
                width: 1200,
                height: 630,
            }),
            uploadPlaceholderMedia({
                alt: 'ML Workshop Banner',
                type: 'event',
                label: 'Intro to ML Workshop',
                bgColor: '#1a3a3e',
                width: 1200,
                height: 630,
            }),
            uploadPlaceholderMedia({
                alt: 'Study Session Banner',
                type: 'event',
                label: 'Semester Study Session',
                bgColor: '#1a2e1a',
                width: 1200,
                height: 630,
            }),
            uploadPlaceholderMedia({
                alt: 'Networking Night Banner',
                type: 'event',
                label: 'Industry Networking Night',
                bgColor: '#2e1a3e',
                width: 1200,
                height: 630,
            }),
            uploadPlaceholderMedia({
                alt: 'Social Night Banner',
                type: 'event',
                label: 'CS Club Social Night',
                bgColor: '#2e1a1a',
                width: 1200,
                height: 630,
            }),
        ]);

    // Project images — 1600×900 (16:9, matches production)
    const [idImgWebsite, idImgTimetable, idImgVoxel] = await Promise.all([
        uploadPlaceholderMedia({
            alt: 'CS Club Website',
            type: 'project',
            label: 'CS Club Website',
            bgColor: '#1a2a3e',
            width: 1600,
            height: 900,
        }),
        uploadPlaceholderMedia({
            alt: 'MyTimetable',
            type: 'project',
            label: 'MyTimetable',
            bgColor: '#1a3a2e',
            width: 1600,
            height: 900,
        }),
        uploadPlaceholderMedia({
            alt: 'Voxel Game Engine',
            type: 'project',
            label: 'Voxel Game Engine',
            bgColor: '#2e2e1a',
            width: 1600,
            height: 900,
        }),
    ]);

    // Gallery images — 5 per album
    const hackathonAlbumName = 'Annual Hackathon 2026';
    const socialAlbumName = 'End-of-Year Social 2025';

    // Gallery images — 1600×900, 5 per album
    const galleryHackathon: string[] = [];
    for (let i = 1; i <= 5; i++) {
        galleryHackathon.push(
            await uploadPlaceholderMedia({
                alt: `${hackathonAlbumName} Photo ${i}`,
                type: 'gallery',
                eventName: hackathonAlbumName,
                label: `Hackathon Photo ${i}`,
                bgColor: '#1a1a2e',
                width: 1600,
                height: 900,
            })
        );
    }

    const gallerySocial: string[] = [];
    for (let i = 1; i <= 5; i++) {
        gallerySocial.push(
            await uploadPlaceholderMedia({
                alt: `${socialAlbumName} Photo ${i}`,
                type: 'gallery',
                eventName: socialAlbumName,
                label: `Social Photo ${i}`,
                bgColor: '#2e1a2e',
                width: 1600,
                height: 900,
            })
        );
    }

    console.log('  ✓ All placeholder media uploaded');

    // -------------------------------------------------------------------------
    // TECH STACK
    // -------------------------------------------------------------------------
    console.log('\n⚙️  Seeding tech stack...');
    const techStackEntries = [
        { 'tech-name': 'Next.js', color: '#B17CA6' },
        { 'tech-name': 'React', color: '#ED8C9B' },
        { 'tech-name': 'TypeScript', color: '#ACCB00' },
        { 'tech-name': 'Tailwind CSS', color: '#907FC3' },
        { 'tech-name': 'Vite', color: '#FFA500' },
        { 'tech-name': 'Supabase', color: '#5DBBB5' },
        { 'tech-name': 'Python', color: '#64B550' },
        { 'tech-name': 'FastAPI', color: '#F6BF00' },
        { 'tech-name': 'Discord.py', color: '#7387CE' },
        { 'tech-name': 'NextUI', color: '#A8DADC' },
        { 'tech-name': 'Pragmatic Drag & Drop', color: '#FF6F61' },
        { 'tech-name': 'Requests', color: '#017DFA' },
        { 'tech-name': 'C++', color: '#5E96D0' },
        { 'tech-name': 'OpenGL', color: '#FFA500' },
        { 'tech-name': 'MongoDB', color: '#00684A' },
    ];

    const tsIds: Record<string, string> = {};
    for (const entry of techStackEntries) {
        const res = await api<{ doc: { id: string } }>('POST', '/tech-stack', entry);
        tsIds[entry['tech-name']] = res.doc.id;
        process.stdout.write('.');
    }
    console.log(`\n  ✓ ${techStackEntries.length} tech stack entries created`);

    // -------------------------------------------------------------------------
    // SPONSORS
    // -------------------------------------------------------------------------
    console.log('\n🏢 Seeding sponsors...');
    const sponsors = [
        {
            'Company name': 'Nexus Financial',
            'Company description':
                'Nexus Financial is a leading quantitative trading firm headquartered in Adelaide, specialising in algorithmic strategies across equities, derivatives, and fixed income markets. We invest heavily in technology talent and partner with universities to foster the next generation of engineers and data scientists.',
            'website link': 'https://example-nexus.com/',
            'sponsor tier': 'gold',
            logo: idGoldLogo,
            _status: 'published',
        },
        {
            'Company name': 'QuantEdge Technologies',
            'Company description':
                'QuantEdge Technologies delivers enterprise-grade data pipelines and machine-learning platforms for financial services clients across Australia and Southeast Asia. Our internship program is one of the most competitive in the region, offering real project ownership from day one.',
            'website link': 'https://example-quantedge.com/',
            'sponsor tier': 'silver',
            logo: idSilverLogo,
            _status: 'published',
        },
        {
            'Company name': 'Ironclad Systems',
            'Company description':
                "Ironclad Systems is an Australian-owned defence technology company with over 20 years of experience delivering mission-critical software for the Department of Defence. We specialise in secure communications, cyber resilience, and real-time embedded systems. We're proud to support Australia's future defence engineers.",
            'website link': 'https://example-ironclad.com/',
            'sponsor tier': 'bronze',
            logo: idBronze1,
            _status: 'published',
        },
        {
            'Company name': 'Wavefront Analytics',
            'Company description':
                'Wavefront Analytics is a data consultancy that helps organisations in healthcare, logistics, and retail transform raw data into actionable insight. We use open-source tooling, cloud-native architectures, and ML to build scalable analytics products.',
            'website link': 'https://example-wavefront.com/',
            'sponsor tier': 'bronze',
            logo: idBronze2,
            _status: 'published',
        },
        {
            'Company name': 'Meridian Defence',
            'Company description':
                'Meridian Defence is a sovereign capability provider supporting the Australian and allied defence sectors with cutting-edge software engineering, decision support, and cyber security solutions. We believe deeply in growing local talent and partnering with universities across South Australia.',
            'website link': 'https://example-meridian.com/',
            'sponsor tier': 'bronze',
            logo: idBronze3,
            _status: 'published',
        },
    ];

    for (const sponsor of sponsors) {
        await api('POST', '/sponsors', sponsor);
        process.stdout.write('.');
    }
    console.log(`\n  ✓ ${sponsors.length} sponsors created`);

    // -------------------------------------------------------------------------
    // PROJECTS
    // -------------------------------------------------------------------------
    console.log('\n🔧 Seeding projects...');
    const ts = tsIds; // shorthand
    const projects = [
        {
            title: 'CS Club Website',
            description:
                'The official website of the Computer Science Club, featuring membership sign-up, event listings, and project showcases.',
            image: idImgWebsite,
            githubLink: 'https://github.com/compsci-adl/website',
            websiteLink: 'https://csclub.org.au',
            techStack: [ts['Next.js'], ts['React'], ts['TypeScript'], ts['Tailwind CSS']],
            isCurrent: 'true',
            _status: 'published',
        },
        {
            title: 'MyTimetable',
            description:
                'An interactive drag-and-drop timetable scheduler to help UofA students optimise their weekly schedule and avoid clashes.',
            image: idImgTimetable,
            githubLink: 'https://github.com/compsci-adl/mytimetable',
            websiteLink: 'https://mytimetable.csclub.org.au/',
            techStack: [
                ts['TypeScript'],
                ts['React'],
                ts['Vite'],
                ts['Pragmatic Drag & Drop'],
                ts['Next.js'],
                ts['Tailwind CSS'],
            ],
            isCurrent: 'true',
            _status: 'published',
        },
        {
            title: 'Voxel Game Engine',
            description:
                'A voxel game engine built from scratch using C++ and OpenGL, featuring procedural terrain generation and a custom chunk-based rendering system.',
            image: idImgVoxel,
            githubLink: 'https://github.com/compsci-adl/voxel-engine',
            techStack: [ts['C++'], ts['OpenGL']],
            isCurrent: 'true',
            _status: 'published',
        },
        {
            title: 'MyVote',
            description:
                "The Computer Science Club's internal election and voting platform, built to run transparent AGM and committee elections.",
            githubLink: 'https://github.com/compsci-adl/myvote',
            techStack: [ts['Next.js'], ts['React'], ts['TypeScript'], ts['Tailwind CSS']],
            isCurrent: 'true',
            _status: 'published',
        },
        {
            title: 'DuckBot',
            description:
                'A multipurpose Discord bot for the CS Club server, handling moderation, event notifications, role assignments, and trivia games.',
            githubLink: 'https://github.com/compsci-adl/duckbot',
            techStack: [ts['Python'], ts['Discord.py']],
            isCurrent: 'true',
            _status: 'published',
        },
        {
            title: 'MyCourseReviews',
            description:
                'A peer-driven platform where UofA students can anonymously share course reviews, difficulty ratings, and study tips.',
            githubLink: 'https://github.com/compsci-adl/course-reviews',
            techStack: [
                ts['Next.js'],
                ts['React'],
                ts['TypeScript'],
                ts['Tailwind CSS'],
                ts['Supabase'],
            ],
            isCurrent: 'false',
            _status: 'published',
        },
        {
            title: 'MyStudyPlan',
            description:
                'A UofA degree planner that lets students explore and validate their degree structure against official program requirements.',
            githubLink: 'https://github.com/compsci-adl/studyplan',
            techStack: [ts['React'], ts['Vite'], ts['TypeScript'], ts['Tailwind CSS']],
            isCurrent: 'false',
            _status: 'published',
        },
        {
            title: 'Grade Calculator API',
            description:
                'A lightweight REST API for calculating weighted GPA and grade distributions from raw assessment data exported from MyUni.',
            githubLink: 'https://github.com/compsci-adl/grade-calculator',
            techStack: [ts['Python'], ts['FastAPI'], ts['Requests']],
            isCurrent: 'false',
            _status: 'published',
        },
    ];

    for (const project of projects) {
        await api('POST', '/projects', project);
        process.stdout.write('.');
    }
    console.log(`\n  ✓ ${projects.length} projects created`);

    // -------------------------------------------------------------------------
    // EVENTS
    // -------------------------------------------------------------------------
    console.log('\n📅 Seeding events...');

    const future = (days: number, hour = 18) => {
        const d = new Date();
        d.setUTCDate(d.getUTCDate() + days);
        d.setUTCHours(hour, 0, 0, 0);
        return d.toISOString();
    };
    const past = (days: number, hour = 18) => {
        const d = new Date();
        d.setUTCDate(d.getUTCDate() - days);
        d.setUTCHours(hour, 0, 0, 0);
        return d.toISOString();
    };

    const events = [
        {
            title: 'Annual Hackathon 2026',
            details:
                'Join us for our biggest hackathon of the year! Compete in teams of up to four across 24 hours of coding, mentoring sessions, and workshops. Massive prizes to be won, plus sponsor networking opportunities with Nexus Financial and QuantEdge Technologies.\n\nAll skill levels welcome — beginners will be paired with experienced mentors. Meals and snacks provided throughout the event.',
            location: 'Ingkarni Wardli, University of Adelaide',
            date: future(14),
            time: { start: future(14, 9), end: future(15, 9) },
            banner: idBannerHackathon,
            link: { Link: 'https://example.com/hackathon-register', displayText: 'Register Now' },
            _status: 'published',
        },
        {
            title: 'Intro to Machine Learning Workshop',
            details:
                'Ever wondered how ChatGPT or Stable Diffusion actually work? This hands-on workshop introduces the core concepts of machine learning — from linear regression to neural networks — with live coding in Python and scikit-learn.\n\nNo prior ML experience needed. Bring your laptop!',
            location: 'Ingkarni Wardli 236',
            date: future(7),
            time: { start: future(7, 17), end: future(7, 19) },
            banner: idBannerWorkshop,
            link: {},
            _status: 'published',
        },
        {
            title: 'Semester 2 Study Session',
            details:
                "📚✏️ Exam season is approaching!\n\nJoin us for the CS Club study session and lock in with fellow students before assessments hit. Whether you need help, want practice problems, or just need a quiet and productive space — we've got you covered.",
            location: 'Engineering and Maths 205',
            date: future(21),
            time: { start: future(21, 11), end: future(21, 16) },
            banner: idBannerStudy,
            link: {},
            _status: 'published',
        },
        {
            title: 'Industry Networking Night',
            details:
                'Connect with industry professionals from companies including Nexus Financial, Ironclad Systems, and Meridian Defence in a relaxed networking setting.\n\nThis event is perfect for students looking for internships, graduate roles, or just wanting to learn about different career paths in the tech industry. Come prepared with your resume!',
            location: 'Ingkarni Wardli 715 Conference Room',
            date: future(28),
            time: { start: future(28, 17), end: future(28, 19) },
            banner: idBannerNetworking,
            link: { Link: 'https://example.com/networking-rsvp', displayText: 'RSVP Here' },
            _status: 'published',
        },
        {
            title: 'CS Club Social Night',
            details:
                "Come hang out with fellow CS students at our semester social event! We'll have board games, trivia, and great vibes.\n\nThis is a relaxed, inclusive event — a great opportunity to meet new people, make friends, and be part of the CS Club community.",
            location: 'The Duck Lounge, Ingkarni Wardli',
            date: future(35),
            time: { start: future(35, 18), end: future(35, 21) },
            banner: idBannerSocial,
            link: {},
            _status: 'published',
        },
        {
            title: 'Cyber Security Panel',
            details:
                'We hosted an exclusive panel featuring industry experts from Cybersecurity, DevSecOps, and Academia. Panellists covered the latest trends in threat intelligence, incident response, and building a career in cyber.',
            location: 'Ingkarni Wardli 715 Conference Room',
            date: past(14),
            time: { start: past(14, 17), end: past(14, 19) },
            banner: idBannerNetworking,
            link: {},
            _status: 'published',
        },
        {
            title: 'Active Directory Workshop',
            details:
                'Think hacking is just typing fast in a black hoodie? 👀 Start with the fundamentals.\n\nWe introduced attendees to Active Directory — one of the most important systems in enterprise cybersecurity. Participants explored how it works and where vulnerabilities commonly appear.',
            location: 'Ingkarni Wardli 236',
            date: past(21),
            time: { start: past(21, 17), end: past(21, 18) },
            banner: idBannerWorkshop,
            link: {},
            _status: 'published',
        },
        {
            title: 'Semester 1 O-Week Kick-off BBQ',
            details:
                'Welcome to CS Club! We kicked off the semester with a free BBQ and meet-and-greet for new and returning students. This was a great opportunity to learn about the club, its projects, events, and how to get involved.',
            location: 'The Duck Lounge, Ingkarni Wardli',
            date: past(60),
            time: { start: past(60, 12), end: past(60, 14) },
            banner: idBannerSocial,
            link: {},
            _status: 'published',
        },
    ];

    for (const event of events) {
        await api('POST', '/events', event);
        process.stdout.write('.');
    }
    console.log(`\n  ✓ ${events.length} events created`);

    // -------------------------------------------------------------------------
    // GALLERY
    // -------------------------------------------------------------------------
    console.log('\n🖼  Seeding gallery albums...');

    // Gallery hook auto-populates images from media with matching eventName
    const galleries = [
        {
            eventName: hackathonAlbumName,
            eventDate: past(14),
            _status: 'published',
        },
        {
            eventName: socialAlbumName,
            eventDate: past(180),
            _status: 'published',
        },
    ];

    for (const gallery of galleries) {
        await api('POST', '/gallery', gallery);
        process.stdout.write('.');
    }
    console.log(
        `\n  ✓ ${galleries.length} gallery albums created (images auto-linked via eventName hook)`
    );

    // -------------------------------------------------------------------------
    // COMMITTEE MEMBERS
    // -------------------------------------------------------------------------
    console.log('\n👥 Seeding committee members...');
    const committeeMembers = [
        // Exec
        { name: 'Jordan Zhang', role: 'President', exec: true },
        { name: 'Priya Sharma', role: 'Vice President', exec: true },
        { name: "Liam O'Brien", role: 'Treasurer', exec: true },
        { name: 'Ananya Patel', role: 'Secretary and Human Resources Officer', exec: true },
        { name: 'Marcus Chen', role: 'Partnerships & Sponsorships Manager', exec: true },
        { name: 'Sofia Nguyen', role: 'Executive Advisor', exec: true },
        { name: 'Ethan Williams', role: 'Executive Advisor', exec: true },
        { name: 'Zara Khan', role: 'Executive Advisor and Open Source Officer', exec: true },
        // Managers
        { name: 'Riley Thompson', role: 'Events Manager', exec: false },
        { name: 'Nadia Kowalski', role: 'Design Manager', exec: false },
        { name: 'Oliver Park', role: 'Open Source & Infrastructure Manager', exec: false },
        { name: 'Isabella Rossi', role: 'Social Media & Marketing Manager', exec: false },
        // Officers
        { name: 'Leo Tanaka', role: 'Events Officer', exec: false },
        { name: 'Mei Lin', role: 'Events Officer', exec: false },
        { name: 'Hamid Ahmadi', role: 'Events Officer', exec: false },
        { name: 'Chloe Dubois', role: 'Design Officer', exec: false },
        { name: 'Rajan Mehta', role: 'Design Officer', exec: false },
        { name: 'Yasmin Al-Farsi', role: 'Social Media & Marketing Officer', exec: false },
        { name: 'Connor Walsh', role: 'Social Media & Marketing Officer', exec: false },
        { name: 'Fatima Osei', role: 'Social Media & Marketing Officer', exec: false },
        { name: 'Ben Larsson', role: 'Open Source Officer', exec: false },
        { name: 'Tanya Ivanova', role: 'Open Source Officer', exec: false },
        { name: 'Dylan Carter', role: 'Open Source Officer', exec: false },
        { name: 'Amara Diallo', role: 'Partnerships & Sponsorships Officer', exec: false },
        { name: 'Lucas Fernandez', role: 'Partnerships & Sponsorships Officer', exec: false },
        { name: 'Sara Johansson', role: 'Duck Lounge Liaison', exec: false },
        { name: 'Kai Nakamura', role: 'Duck Lounge Liaison', exec: false },
        { name: 'Gabrielle Martin', role: 'First Year Representative', exec: false },
        { name: 'Arjun Singh', role: 'Postgraduate Representative', exec: false },
    ].map((m) => ({ ...m, _status: 'published' }));

    for (const member of committeeMembers) {
        await api('POST', '/committee-members', member);
        process.stdout.write('.');
    }
    console.log(`\n  ✓ ${committeeMembers.length} committee members created`);

    // -------------------------------------------------------------------------
    // NOTIFICATION GLOBAL
    // -------------------------------------------------------------------------
    console.log('\n🔔 Seeding notification global...');
    await api('POST', '/globals/notification', {
        enabled: true,
        type: 'banner',
        text: '🎉 Annual Hackathon registrations are now open!',
        url: 'https://example.com/hackathon-register',
        urlText: 'Register Now',
    });
    console.log('  ✓ Notification global set');

    console.log('\n✅ Seeding complete!\n');
}

main().catch((err) => {
    console.error('\n❌ Seeding failed:', err.message ?? err);
    process.exit(1);
});
