name: Linting and Formatting Checks
on:
  workflow_call:

permissions:
  contents: read

jobs:
  es-lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run format:check
