name: Linting and Formatting Checks
on:
  workflow_call:

permissions:
  contents: read

jobs:
  es-lint:
    name: ESLint
    runs-on: ubuntu-latest

    env:
      SKIP_INSTALL_SIMPLE_GIT_HOOKS: '1'
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e
        with:
          version: 11
      - run: pnpm install --ignore-scripts
      - run: pnpm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    env:
      SKIP_INSTALL_SIMPLE_GIT_HOOKS: '1'
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e
        with:
          version: 11
      - run: pnpm install --ignore-scripts
      - run: pnpm run format:check
