name: Lint
on:
  pull_request:
    branches:
      - '*'
  push:
    branches: [main, ci]

jobs:
  es-lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: pnpm install
      - run: pnpm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: pnpm install
      - run: pnpm run format:check
