name: Main

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - production

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Call Lint Workflow
        uses: compsci-adl/website/.github/workflows/lint.yml@aws

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: lint
    steps:
      - name: Call Build Workflow
        uses: compsci-adl/website/.github/workflows/build.yml@aws

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    steps:
      - name: Call Deploy Workflow
        uses: compsci-adl/website/.github/workflows/deploy.yml@aws
